[
github
]
token = "tu_token_de_github_personal"  # Este token necesita permisos de 'repo'
owner = "tu_nombre_de_usuario"
repo = "nombre_de_tu_repositorio"
branch = "main"  # o master, dependiendo de tu configuración
